---

- hosts: localhost
  sudo: no
  vars:
    - dotfiles:
        - boot
        - gitconfig
        - gitignore
        - jsbeautifyrc
        - lein
        - nvmrc
        - vim
        - vimrc
        - gvimrc
        - spacemacs
        - tmux.conf
        - zshrc
        - ssh/rc
    - home_dir: "{{ '~' | expanduser }}"

  tasks:
    - name: oh-my-zsh and spacemacs
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: master
        accept_hostkey: yes
      with_items:
        - repo: git://github.com/robbyrussell/oh-my-zsh.git
          dest: ~/.oh-my-zsh
        - repo: https://github.com/syl20bnr/spacemacs
          dest: ~/.emacs.d

    - debug: var=home_dir

    - name: Back up all the files to be updated
      shell: mv ~/.{{ item }} ~/.{{ item }}.bak.$(date +%s)
      with_items: dotfiles
      ignore_errors: yes

    - name: Create dotfile symlinks
      file:
        dest: "{{ home_dir }}/.{{ item }}"
        src: "{{ home_dir }}/.dots/dotfiles/{{ item }}"
        force: yes
        backup: yes
        state: link
      with_items: dotfiles

    - name: Clone Vundle plugin
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "{{ home_dir }}/.vim/bundle/Vundle.vim"
        version: master
        accept_hostkey: yes

    # Silly trick: redirect a file as input to Vim so that it gets past the
    # warning messages
    - name: Install Vim plugins via Vundle
      shell: vim +PluginInstall! +PluginClean +qall < ansible-install.yml
