---

- hosts: localhost
  sudo: no
  vars:
    - dotfiles:
        - boot
        - config/nvim
        - gitconfig
        - gitignore
        - jsbeautifyrc
        - lein
        - matplotlib
        - nvmrc
        - vim
        - vimrc
        - gvimrc
        - spacemacs
        - tmux.conf
        - zshrc
        - zshenv
        - ssh/rc
    - home_dir: "{{ '~' | expanduser }}"

  tasks:
    - name: oh-my-zsh and spacemacs
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: master
        accept_hostkey: yes
      with_items:
        - repo: git://github.com/robbyrussell/oh-my-zsh.git
          dest: ~/.oh-my-zsh
        - repo: https://github.com/syl20bnr/spacemacs
          dest: ~/.emacs.d

    - debug: var=home_dir

    - name: Back up all the files to be updated if they are not already symlinks
      shell: test -f {{ item }} && mv ~/.{{ item }} ~/.{{ item }}.bak.$(date +%s)
      with_items: dotfiles
      ignore_errors: yes

    - name: Create dotfile symlinks
      file:
        dest: "{{ home_dir }}/.{{ item }}"
        src: "{{ home_dir }}/.dots/dotfiles/{{ item }}"
        force: yes
        backup: yes
        state: link
      with_items: dotfiles

    ## Vim ##
    - name: Clone Vundle plugin
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "{{ home_dir }}/.vim/bundle/Vundle.vim"
        version: master
        accept_hostkey: yes

    # Silly trick: redirect a file as input to Vim so that it gets past the
    # warning messages
    - name: Install Vim plugins via Vundle
      shell: vim +PluginInstall! +PluginClean +qall < ansible-install.yml

    ## NVim ##
    - name: Create nvim autoload dir
      file:
        path: "{{ home_dir }}/.config/nvim/autoload"
        state: directory

    - name: Install vim-plug plugin to nvim
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ home_dir }}/.config/nvim/autoload/plug.vim"

    # Silly trick: redirect a file as input to Vim so that it gets past the
    # warning messages
    - name: Install nvim plugins via Plug
      shell: nvim +PlugInstall! +PlugClean +qall < ansible-install.yml
